[package]
name = "grandium-core"
description = "Platform-independent logic for Grandium"
version.workspace = true
edition.workspace = true

[dependencies]
nucleo-matcher = "0.3"
png = "0.17"
serde = { version = "1", features = ["derive"] }
unicode-segmentation = "1"

[dev-dependencies]
serde_json = "1"
